
MODULE accelpy_global
    USE, INTRINSIC :: ISO_C_BINDING
    IMPLICIT NONE

INTEGER (C_INT64_T), DIMENSION(:), POINTER :: a
INTEGER (C_INT64_T), DIMENSION(:), POINTER :: b
INTEGER (C_INT64_T), DIMENSION(:), POINTER :: c

END MODULE
