INTEGER (C_INT) FUNCTION add1d(ATTR_LEN, ATTR, X, Y, Z) BIND(C, name="add1d")
USE ISO_C_BINDING, ONLY: C_INT, C_DOUBLE
IMPLICIT NONE

INTEGER(C_INT), INTENT(IN) :: ATTR_LEN 
INTEGER(C_INT), DIMENSION(ATTR_LEN), INTENT(IN) :: ATTR
REAL(C_DOUBLE), DIMENSION(ATTR(1)), INTENT(IN) :: X 
REAL(C_DOUBLE), DIMENSION(ATTR(1)), INTENT(IN) :: Y 
REAL(C_DOUBLE), DIMENSION(ATTR(1)), INTENT(OUT) :: Z 

integer i

DO i=1, ATTR(1)
        Z(i) = X(i) + Y(i)
END DO

add1d = 0
END FUNCTION
