INTEGER (C_INT) FUNCTION add1d(x, y, z) BIND(C, name="add1d")
USE ISO_C_BINDING, ONLY: C_INT, C_DOUBLE
IMPLICIT NONE

REAL(C_DOUBLE), INTENT(IN) :: x 
REAL(C_DOUBLE), INTENT(IN) :: y 
REAL(C_DOUBLE), INTENT(OUT) :: z 

z = x + y

add1d = 0
END FUNCTION
