INTEGER (C_INT) FUNCTION add1d(ARR_LEN, X, Y, Z) BIND(C, name="add1d")
USE ISO_C_BINDING, ONLY: C_INT, C_DOUBLE
IMPLICIT NONE

INTEGER(C_INT), INTENT(IN) :: ARR_LEN 
REAL(C_DOUBLE), DIMENSION(ARR_LEN), INTENT(IN) :: X 
REAL(C_DOUBLE), DIMENSION(ARR_LEN), INTENT(IN) :: Y 
REAL(C_DOUBLE), DIMENSION(ARR_LEN), INTENT(OUT) :: Z 

integer i

DO i=1, ARR_LEN
        Z(i) = X(i) + Y(i)
END DO

add1d = 0
END FUNCTION
